"""Initial table creation

Revision ID: 358381576183
Revises: 
Create Date: 2019-03-24 17:49:04.673137

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '358381576183'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('most_used_routes',
    sa.Column('route_id', sa.String(), nullable=False),
    sa.Column('start_station_name', sa.String(), nullable=True),
    sa.Column('end_station_name', sa.String(), nullable=True),
    sa.Column('num_trips', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('route_id')
    )
    op.create_index(op.f('ix_most_used_routes_end_station_name'), 'most_used_routes', ['end_station_name'], unique=False)
    op.create_index(op.f('ix_most_used_routes_start_station_name'), 'most_used_routes', ['start_station_name'], unique=False)
    op.create_table('trip_fact',
    sa.Column('tripduration', sa.Integer(), nullable=True),
    sa.Column('starttime', sa.String(), nullable=True),
    sa.Column('stoptime', sa.String(), nullable=True),
    sa.Column('start_station_id', sa.Integer(), nullable=True),
    sa.Column('start_station_name', sa.String(), nullable=True),
    sa.Column('start_station_latitude', sa.Float(), nullable=True),
    sa.Column('start_station_longitude', sa.Float(), nullable=True),
    sa.Column('end_station_id', sa.Integer(), nullable=True),
    sa.Column('end_station_name', sa.String(), nullable=True),
    sa.Column('end_station_latitude', sa.Float(), nullable=True),
    sa.Column('end_station_longitude', sa.Float(), nullable=True),
    sa.Column('bikeid', sa.String(), nullable=True),
    sa.Column('usertype', sa.String(), nullable=True),
    sa.Column('birth_year', sa.Integer(), nullable=True),
    sa.Column('gender', sa.Integer(), nullable=True)
    )
    op.create_index(op.f('ix_trip_fact_end_station_name'), 'trip_fact', ['end_station_name'], unique=False)
    op.create_index(op.f('ix_trip_fact_start_station_name'), 'trip_fact', ['start_station_name'], unique=False)
    op.create_table('trip_fact_stg',
    sa.Column('tripduration', sa.Integer(), nullable=True),
    sa.Column('starttime', sa.String(), nullable=True),
    sa.Column('stoptime', sa.String(), nullable=True),
    sa.Column('start_station_id', sa.Integer(), nullable=True),
    sa.Column('start_station_name', sa.String(), nullable=True),
    sa.Column('start_station_latitude', sa.Float(), nullable=True),
    sa.Column('start_station_longitude', sa.Float(), nullable=True),
    sa.Column('end_station_id', sa.Integer(), nullable=True),
    sa.Column('end_station_name', sa.String(), nullable=True),
    sa.Column('end_station_latitude', sa.Float(), nullable=True),
    sa.Column('end_station_longitude', sa.Float(), nullable=True),
    sa.Column('bikeid', sa.String(), nullable=True),
    sa.Column('usertype', sa.String(), nullable=True),
    sa.Column('birth_year', sa.Integer(), nullable=True),
    sa.Column('gender', sa.Integer(), nullable=True)
    )
    op.create_index(op.f('ix_trip_fact_stg_end_station_name'), 'trip_fact_stg', ['end_station_name'], unique=False)
    op.create_index(op.f('ix_trip_fact_stg_start_station_name'), 'trip_fact_stg', ['start_station_name'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_trip_fact_stg_start_station_name'), table_name='trip_fact_stg')
    op.drop_index(op.f('ix_trip_fact_stg_end_station_name'), table_name='trip_fact_stg')
    op.drop_table('trip_fact_stg')
    op.drop_index(op.f('ix_trip_fact_start_station_name'), table_name='trip_fact')
    op.drop_index(op.f('ix_trip_fact_end_station_name'), table_name='trip_fact')
    op.drop_table('trip_fact')
    op.drop_index(op.f('ix_most_used_routes_start_station_name'), table_name='most_used_routes')
    op.drop_index(op.f('ix_most_used_routes_end_station_name'), table_name='most_used_routes')
    op.drop_table('most_used_routes')
    # ### end Alembic commands ###
